version: "3.8"
services:
  #* postgres database
  db:
    image: postgres:15.18-bookworm
    container_name: postgresDatabase
    env_file:
      - ./database.env
    volumes:
      - ./db_data.dev:/var/lib/postgresql/data